springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha

public-data:
  base-url: https://apis.data.go.kr
  service-key: ${PUBLIC_DATA_SERVICE_KEY}